version: "3"
services:
  client-react:
    container_name: client-react
    build: .
    ports:
      - "5173:5173"
    volumes:
      - ./src:/opt/app/src
      - ./package.json:/opt/package.json
      - ./public:/opt/app/public